# Generated by Django 5.0.6 on 2024-07-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
